[build]
  base = "frontend/vue-project/"
  publish = "frontend/vue-project/dist"
  command = "npm run build"

# The following redirect is intended for use with most SPAs
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200