# Generated by Django 4.0.5 on 2022-07-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(default='posts/preview_images/default.jpg', upload_to='posts/preview_images/'),
        ),
    ]
