# Generated by Django 4.0.5 on 2022-08-31 10:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
